title: Zach Langford
description: >-
    <a href='/index'>Home</a> | <a href='/cv'>CV</a> | <a href='/contact'>Contact</a>

github_username:  langfordzl

# Build settings
markdown: kramdown
theme: jekyll-theme-minima
plugins:
  - jekyll-feed
