title: Zach Langford
description: PhD
github_username:  langfordzl

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

```{css my-header-colors, echo = FALSE}
.page-header {
    background-image: linear-gradient(120deg, red, orange);
}
```
